### ISSUE TITLE
no review without demo in Docker

### ISSUE THREAD

**Issue by rcemper** [intersystems/isc-ipm-js#7]

**Comment by isc-tleavitt** [comment]
@rcemper As a building block for applications, I don't think it makes sense for this package to have its own Docker demo. If I was to create a demo for this, it would be via https://github.com/intersystems/isc-perf-ui (which is not of much practical use in a Docker container all on its own) or perhaps the sample app at https://github.com/intersystems/isc-rest/tree/main/samples/phonebook.

**Comment by rcemper** [comment]
It's just an information why I would not provide a review nor other quality checks without
the ability to remove 100% of all checked stuff after examination without any traces.
Docker is the only way to keep my equipment clean with my limited resources by affordable effort.
